Log 클래스 추가
myLittleWebserv/myLittleWebserv pull request #22
Opened 2022-08-19 15:38 UTC by JaemooJung

Log class를 추가하였습니다.
전역에 static으로 log 상수를 선언해두어 다음과 같이 사용할 수 있습니다.

로그 상에 mark를 남기고 싶을 때
* `log.mark("message")`

로그를 남기고 싶을 때
* `log(__FILE__, __LINE__, __func__, "message", TYPE)`

__FILE__, __LINE__, __func__ 는 매크로 함수로 반드시 로그를 호출하는 단에서 파라미터로 넣어주어야 합니다!!!!

2022-08-19 17:48 UTC, 42mypark commented on Log/Log.hpp
> +static Log log;
전역변수로 선언하면 여러 파일에서 Log.hpp include하고 컴파일하면 링킹 과정에서 문제가 발생할 거 같습니다.
저도 이전에 이런 방식으로 작성했다가 안됐었거든요... ㅜ_ㅜ

2022-08-19 17:52 UTC, 42mypark requested changes
한번 해보기....

2022-08-20 03:38 UTC, JaemooJung commented on Log/Log.hpp
> +static Log log;
흐앙 ㅠㅠㅠ 그러면 어쩔수 없이 다시 싱글톤으로 가야겠네얌... 주르륵....

2022-08-20 03:38 UTC, JaemooJung commented on Log/Log.hpp
> +static Log log;
수정해서 올리겠슴다!

2022-08-20 03:49 UTC, closed without merging